kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: Authenticate-eihle8
  namespace: DPNano_Product_Weather
  version: '1'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  operation:
    apiDefinition: {}
